apiVersion: v1
kind: Pod
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  containers:
    - name: airflow
      image: apache/airflow
      command: ["bash", "-c"]
      args:
        - airflow db migrate && airflow api-server
      env:
        - name: LOAD_EX
          value: "y"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
